package com.chen.domain;

import com.chen.base.model.BaseAdminTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminTable extends BaseAdminTable<AdminTable> {
	public static final AdminTable dao = new AdminTable();
}
