package com.chen.domain;

import com.chen.base.model.BaseDbExamer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DbExamer extends BaseDbExamer<DbExamer> {
	public static final DbExamer dao = new DbExamer();
}
