package com.chen.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDbExamer<M extends BaseDbExamer<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public void setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
	}

	public java.lang.String getIdCard() {
		return get("id_card");
	}

	public void setSchool(java.lang.String school) {
		set("school", school);
	}

	public java.lang.String getSchool() {
		return get("school");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public void setPcId(java.lang.Integer pcId) {
		set("pc_id", pcId);
	}

	public java.lang.Integer getPcId() {
		return get("pc_id");
	}

}
