package com.chen.domain;

import com.chen.base.model.BaseStlxb;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Stlxb extends BaseStlxb<Stlxb> {
	public static final Stlxb dao = new Stlxb();
}
