package com.chen.domain;

import com.chen.base.model.BaseStlbb;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Stlbb extends BaseStlbb<Stlbb> {
	public static final Stlbb dao = new Stlbb();
}
