package com.chen.domain;

import com.chen.base.model.BaseStdlb;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Stdlb extends BaseStdlb<Stdlb> {
	public static final Stdlb dao = new Stdlb();
}
