package com.chen.domain;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("admin_table", "id", AdminTable.class);
		arp.addMapping("cjd", "id", Cjd.class);
		arp.addMapping("db_examer", "id", DbExamer.class);
		arp.addMapping("db_pc", "id", DbPc.class);
		// Composite Primary Key order: ID,TMID
		arp.addMapping("stcwb", "ID,TMID", Stcwb.class);
		arp.addMapping("stdlb", "ID", Stdlb.class);
		arp.addMapping("stlbb", "ID", Stlbb.class);
		arp.addMapping("stlxb", "ID", Stlxb.class);
		arp.addMapping("stxxb", "ID", Stxxb.class);
		arp.addMapping("test_1", "id", Test1.class);
	}
}

