package com.chen.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStxxb<M extends BaseStxxb<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public void setSTLB(java.lang.Integer STLB) {
		set("STLB", STLB);
	}

	public java.lang.Integer getSTLB() {
		return get("STLB");
	}

	public void setSTDL(java.lang.Integer STDL) {
		set("STDL", STDL);
	}

	public java.lang.Integer getSTDL() {
		return get("STDL");
	}

	public void setSTLX(java.lang.Integer STLX) {
		set("STLX", STLX);
	}

	public java.lang.Integer getSTLX() {
		return get("STLX");
	}

	public void setSTTM(java.lang.String STTM) {
		set("STTM", STTM);
	}

	public java.lang.String getSTTM() {
		return get("STTM");
	}

	public void setIMAGE(java.lang.String IMAGE) {
		set("IMAGE", IMAGE);
	}

	public java.lang.String getIMAGE() {
		return get("IMAGE");
	}

	public void setXXA(java.lang.String XXA) {
		set("XXA", XXA);
	}

	public java.lang.String getXXA() {
		return get("XXA");
	}

	public void setXXB(java.lang.String XXB) {
		set("XXB", XXB);
	}

	public java.lang.String getXXB() {
		return get("XXB");
	}

	public void setXXC(java.lang.String XXC) {
		set("XXC", XXC);
	}

	public java.lang.String getXXC() {
		return get("XXC");
	}

	public void setXXD(java.lang.String XXD) {
		set("XXD", XXD);
	}

	public java.lang.String getXXD() {
		return get("XXD");
	}

	public void setZQDA(java.lang.String ZQDA) {
		set("ZQDA", ZQDA);
	}

	public java.lang.String getZQDA() {
		return get("ZQDA");
	}

	public void setSTJX(java.lang.String STJX) {
		set("STJX", STJX);
	}

	public java.lang.String getSTJX() {
		return get("STJX");
	}

}
