package com.chen.domain;

import com.chen.base.model.BaseStxxb;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Stxxb extends BaseStxxb<Stxxb> {
	public static final Stxxb dao = new Stxxb();
}
