package com.chen.domain;

import com.chen.base.model.BaseStcwb;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Stcwb extends BaseStcwb<Stcwb> {
	public static final Stcwb dao = new Stcwb();
}
