package com.chen.domain;

import com.chen.base.model.BaseCjd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cjd extends BaseCjd<Cjd> {
	public static final Cjd dao = new Cjd();
}
