package com.chen.domain;

import com.chen.base.model.BaseDbPc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DbPc extends BaseDbPc<DbPc> {
	public static final DbPc dao = new DbPc();
}
