package com.chen.domain;

import com.chen.base.model.BaseTest1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Test1 extends BaseTest1<Test1> {
	public static final Test1 dao = new Test1();
}
